
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 800m
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 9000
        fsGroup: 9000
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsGroup: 9000
      restartPolicy: Always
      schedulerName: default-scheduler
