apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: case4-
namespace: case4
resources:
  - ../../base
configMapGenerator:
- name: config
  files:
  - data.png
patches:
- path: deployment.yaml
