
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
spec:
  template:
    spec:
      containers:
      - name: hello-app
        envFrom:
        - secretRef:
            name: secret
            optional: false
